# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moat < Formula
  desc "Run AI agents in isolated containers with credential injection and full observability"
  homepage "https://majorcontext.com/moat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/moat/releases/download/v0.1.0/moat_0.1.0_darwin_amd64.tar.gz"
      sha256 "b9357fc272bce5af589b36cbcd2b9bfbc3d2a4c1877e611ef2ae31af6512ea96"

      def install
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/moat/releases/download/v0.1.0/moat_0.1.0_darwin_arm64.tar.gz"
      sha256 "33f8ecd6ac1574b1931e2c495956c506be5893cef2aceb88230600ba32a86150"

      def install
        bin.install "moat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.1.0/moat_0.1.0_linux_amd64.tar.gz"
      sha256 "c4cdd1f5492b5890ff2b2e14e8f5178ea25502470101327c9fc9ab3a8e42d8a4"
      def install
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.1.0/moat_0.1.0_linux_arm64.tar.gz"
      sha256 "f66f35bc2c7dde9118a229432d0d9e2dda2595e142eb4de7080e1f1f26e9a00a"
      def install
        bin.install "moat"
      end
    end
  end

  test do
    system "#{bin}/moat", "version"
  end
end
